// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.UI_Produtos;

namespace Projeto.UI_Produtos.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210707034802_Restore")]
    partial class Restore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto.UI_Produtos.Models.CategoriaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaProduto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Eletrodomésticos",
                            Nome = "Eletrônico"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Produtos para Informática",
                            Nome = "Informática"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Aparelhos e acessórios",
                            Nome = "Celulares"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Artigos para vestuário em geral",
                            Nome = "Moda"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "Livros",
                            Nome = "Livros"
                        });
                });

            modelBuilder.Entity("Projeto.UI_Produtos.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Perecivel")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Projeto.UI_Produtos.Models.Produto", b =>
                {
                    b.HasOne("Projeto.UI_Produtos.Models.CategoriaProduto", null)
                        .WithMany()
                        .HasForeignKey("CategoriaProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
